# .pre-commit-config.yaml
# 预提交钩子配置文件
# 详见: https://pre-commit.com

# 默认的全局设置
default_stages: [pre-commit]

repos:
  # Ruff: 一个极速的 Python Linter，可以替代 Flake8, isort, pyupgrade 等
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.5.5 # 建议定期更新到最新版本
  #   hooks:
      # 在暂存的文件上运行 linter
      # - id: ruff
      #  args: [--fix, --show-fixes, --exit-non-zero-on-fix]
      # 在暂存的文件上运行格式化工具 (替代 isort)
      # - id: ruff-format

  # Black: 无妥协的代码格式化工具
  - repo: https://github.com/psf/black
    rev: 24.4.2 # 建议定期更新到最新版本
    hooks:
      - id: black
        # 设置行长，可以根据团队规范调整
        args: [--line-length=120] 