# This workflow will upload Python Packages to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Upload Python Packages

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    name: Build ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [agentkit, loguru-support]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: python -m pip install build

      - name: Build release distributions
        working-directory: ./packages/${{ matrix.package }}
        run: python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.package }}
          path: packages/${{ matrix.package }}/dist/

  pypi-publish:
    name: Publish ${{ matrix.package }} to PyPI
    runs-on: ubuntu-latest
    needs: release-build
    strategy:
      matrix:
        package: [agentkit, loguru-support]
    permissions:
      id-token: write # This is required for trusted publishing
    environment:
      name: pypi
      url: https://pypi.org/p/yai-nexus-${{ matrix.package }} # OPTIONAL: Adjust package name if needed
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: dist-${{ matrix.package }}
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
