name: Reusable PyPI Publish

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
        description: 'The PyPI package name (e.g., yai-nexus-agentkit)'
      package-path:
        required: true
        type: string
        description: 'The relative path to the package directory (e.g., ./packages/agentkit)'
      python-version:
        required: false
        type: string
        default: '3.11'
        description: 'Python version to use'
      pypi-url:
        required: true
        type: string
        description: 'PyPI project URL for environment'

jobs:
  publish:
    name: Publish ${{ inputs.package-name }} to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for trusted publishing
    environment:
      name: pypi
      url: ${{ inputs.pypi-url }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install build dependencies
        run: python -m pip install build

      - name: Build release distributions
        working-directory: ${{ inputs.package-path }}
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ${{ inputs.package-path }}/dist/