# .github/workflows/lint.yml
name: Lint

on: [push, pull_request]

jobs:
  ruff:
    name: Ruff Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run ruff
        uses: chartboost/ruff-action@v1