name: Test Publish Workflows

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ '.github/workflows/**' ]

jobs:
  # Test basic workflow syntax
  test-syntax:
    name: Test workflow syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test basic functionality
        run: |
          echo "✅ Workflow started successfully"
          echo "✅ No startup_failure detected"
          echo "Current ref: ${{ github.ref }}"
          echo "Current ref_name: ${{ github.ref_name }}"

  # Test NPM reusable workflow (dry run)
  test-npm-workflow:
    name: Test NPM reusable workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Simulate NPM workflow call
        run: |
          echo "Testing NPM workflow parameters:"
          echo "Package: @yai-nexus/fekit"
          echo "Path: ./packages/fekit"
          echo "Filter: @yai-nexus/fekit"
          echo "✅ NPM workflow parameters valid"

  # Test PyPI reusable workflow (dry run)
  test-pypi-workflow:
    name: Test PyPI reusable workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Simulate PyPI workflow call
        run: |
          echo "Testing PyPI workflow parameters:"
          echo "Package: yai-nexus-agentkit"
          echo "Path: ./packages/agentkit"
          echo "✅ PyPI workflow parameters valid"
          echo "✅ No environment configuration issues"

  # Test release tag conditions
  test-tag-conditions:
    name: Test release tag conditions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test tag matching logic
        run: |
          echo "Testing tag conditions:"

          # Simulate different tag scenarios
          tags=("v0.3.3" "fekit-v0.3.3" "agentkit-v0.3.3" "loglayer-support-v0.3.3" "loguru-support-v0.3.3")

          for tag in "${tags[@]}"; do
            echo "Testing tag: $tag"

            # Test v* condition
            if [[ $tag == v* ]]; then
              echo "  ✅ Matches v* condition - will publish all packages"
            fi

            # Test specific package conditions
            if [[ $tag == fekit-v* ]]; then
              echo "  ✅ Matches fekit-v* condition - will publish fekit"
            fi

            if [[ $tag == agentkit-v* ]]; then
              echo "  ✅ Matches agentkit-v* condition - will publish agentkit"
            fi

            if [[ $tag == loglayer-support-v* ]]; then
              echo "  ✅ Matches loglayer-support-v* condition - will publish loglayer-support"
            fi

            if [[ $tag == loguru-support-v* ]]; then
              echo "  ✅ Matches loguru-support-v* condition - will publish loguru-support"
            fi

            echo ""
          done