name: Test Publish

on:
  workflow_dispatch:

jobs:
  test-npm:
    name: Test NPM workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo test
        run: echo "NPM workflow test"

  test-pypi:
    name: Test PyPI workflow  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo test
        run: echo "PyPI workflow test"